server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: root

jwt:
  secret: mySecretKey
  expiration: 3600000
